// TODO: Replace with file generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDj68qpIhpZPabkA9HOylZNNCBN5rg9jvE",
    authDomain: "esync-demo-26004.firebaseapp.com",
    databaseURL:
        "https://esync-demo-26004-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "esync-demo-26004",
    storageBucket: "esync-demo-26004.appspot.com",
    messagingSenderId: "784680862624",
    appId: "1:784680862624:web:c1e48785c8a3d3981a5ac5",
    measurementId: "G-JL53C5JECS",
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyB3Hwjx5rysOnjf_NoK3ghQqd8LhFQfy8k',
      appId: "1:784680862624:android:885a3a9b41bdd19a1a5ac5",
      messagingSenderId: "784680862624",
      projectId: "esync-demo-26004",
      databaseURL:
          "https://esync-demo-26004-default-rtdb.asia-southeast1.firebasedatabase.app");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhxOPq-dLt76OwG1QLyvAf2HGpzIfnwA',
    appId: '1:784680862624:ios:dbaa1bd3d2b2e1d21a5ac5',
    messagingSenderId: '784680862624',
    projectId: 'esync-demo-26004',
    databaseURL:
        "https://esync-demo-26004-default-rtdb.asia-southeast1.firebasedatabase.app",
  );
}
